---
apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: Instance
metadata:
  name: crossplane-demo-aws-ec2
spec:
  forProvider:
    imageId: ami-06ce824c157700cd2
    instanceType: t2.micro
    region: eu-central-1
    tags:
      - key: demo
        value: crossplane
      - key: crossplane-kind
        value: instance.ec2.aws.crossplane.io
      - key: crossplane-name
        value: crossplane-demo-aws-ec2
      - key: crossplane-providerconfig
        value: crossplane-demo-aws
  providerConfigRef:
    name: crossplane-demo-aws
