---
apiVersion: ec2.aws.crossplane.io/v1alpha1
kind: Instance
metadata:
  name: crossplane-demo-aws-ec2
spec:
  forProvider:
    imageId: ami-06ce824c157700cd2
    instanceType: t2.micro
    region: eu-central-1
    tags:
      - key: demo
        value: crossplane
  providerConfigRef:
    name: crossplane-demo-aws
