---
apiVersion: ec2.aws.crossplane.io/v1beta1
kind: VPC
metadata:
  name: crossplane-demo-aws-vpc
spec:
  forProvider:
    cidrBlock: 10.0.0.0/16
    enableDnsHostNames: true
    enableDnsSupport: true
    instanceTenancy: default
    region: eu-central-1
    tagSpecifications:
      - resourceType: instance
        tags:
          - key: demo
            value: crossplane
  providerConfigRef:
    name: crossplane-demo-aws
